apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-configmap
  labels:
    app.kubernetes.io/instance: hello-world
data:
  "index.html": |-
    <!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="utf-8">
          <title>GitOpsians! Hello World</title>
        </head>
          <body>
            <h1>Hello GitOpsians!!</h1>
            <br/>
            <h2>
            Demo of a super basic web application
            </h2>
          </body>
      </html>
